name: Clippy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
<<<<<<< HEAD
      - name: Run clippy
        run: make lint
  
=======
          name: linting
          run: make lint

>>>>>>> c33c6e0 (add toml file)
